### ISSUE TITLE
Symbol not found: _OBJC_CLASS_$_SUUpdater

### ISSUE THREAD

**Issue by lanwen** [abemedia/go-sparkle#7]
Hello, thank you for all the work providing these bindings. 

I tried to use them on my project and faced an error which I can't understand - perhaps, that somehow related to M1. Would you be so kind to help me figure out the issue?

I run `testdata/main.go` and immediately get a crash with `dyld[68325]: Symbol not found: _OBJC_CLASS_$_SUUpdater`

Full log:
```
go run testdata/main.go
# github.com/abemedia/go-sparkle
sparkle.m:7:8: warning: 'SUUpdater' is deprecated: Deprecated in Sparkle 2. Use SPUStandardUpdaterController instead, or SPUUpdater if you need more control. [-Wdeprecated-declarations]
../Sparkle.framework/Headers/SUUpdater.h:41:1: note: 'SUUpdater' has been explicitly marked deprecated here
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
sparkle.m:11:27: warning: 'SUUpdater' is deprecated: Deprecated in Sparkle 2. Use SPUStandardUpdaterController instead, or SPUUpdater if you need more control. [-Wdeprecated-declarations]
../Sparkle.framework/Headers/SUUpdater.h:41:1: note: 'SUUpdater' has been explicitly marked deprecated here
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
dyld[68325]: Symbol not found: _OBJC_CLASS_$_SUUpdater
  Referenced from: <EECC1A80-CFA2-34FD-8A7E-F34CB2927493> /private/var/folders/55/wfj6z5ps1016qhrhfk2j9fn80000gn/T/go-build3922016138/b001/exe/main
  Expected in:     <no uuid> unknown
```

**Comment by abemedia** [comment]
Hi,

Thanks for reporting this. The code in main cannot actually be run directly. It needs to be inside a `.app` package.

That said I did recently update the dependencies without changing the code and I'm seeing deprecation warnings in your logs so it looks like this needs some work to move to the latest supported API.

I'll have some time to do so over the weekend and will also add a full example. If you cannot wait the current version should also work using the deprecated API though if you create a .app package with a valid .plist file and run that.

**Comment by lanwen** [comment]
I tried to follow instructions and place `Sparkle.framework` within the app bundle and that didn't work with the same crash. I use https://github.com/getlantern/systray as the main loop as well as the dedicated menu item to trigger the update check. However, the app doesn't start at all. I would greatly appreciate a complete example

**Comment by lanwen** [comment]
I actually found, that it could be related to the fact it can't locate symbols during runtime from the framework. Perhaps, I'm missing something, but is there a way to debug it? Like print somehow where it's trying to find, or during the linking process embed additional info? Maybe there is a way to statically link everything into a single binary?

**Comment by abemedia** [comment]
I've just added an example: https://github.com/abemedia/go-sparkle/tree/master/example
If you check out the [build.sh](https://github.com/abemedia/go-sparkle/blob/master/example/build.sh), that should give you an idea of how to build your application.

I've also added some instructions to the readme as the `rpath` also requires setting in your binary e.g.
```
install_name_tool -add_rpath @loader_path/../Frameworks YourBundle.app/Contents/MacOS/your_binary
```

Also, please ensure you're using the correct version of Sparkle. For the latest go-sparkle version that would be `2.5.1`.

**Comment by lanwen** [comment]
Just in case: https://github.com/abemedia/go-sparkle/pull/18
